[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
 
[project]
name = "kozax"
version = "0.0.14"
description = "Genetic programming library in JAX."
readme = "README.md"
license = {file = "LICENSE.md"}
requires-python = ">=3.9"
authors = [
    {name = "Sigur de Vries", email = "sigur@hotmail.nl"},
    ]
keywords = ["JAX", "Genetic programming", "Symbolic regression", "Evolutionary algorithms"]
url = {repository = "https://github.com/sdevries0/kozax"}
dependencies = [
    "jax>=0.7.0",
    "sympy>=1.13.3",
    "optax>=0.2.3",
    "jaxtyping">=0.3.9"
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Natural Language :: English",
]   
[tool.hatch.build]
include = ["kozax/*"]